"""empty message

Revision ID: 5586623b27c3
Revises: 946d8a2ab755
Create Date: 2023-07-17 13:15:53.076924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5586623b27c3'
down_revision = '946d8a2ab755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('palette',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'eyeshadows', 'palette', ['palette_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eyeshadows', type_='foreignkey')
    op.drop_table('palette')
    # ### end Alembic commands ###
