"""empty message

Revision ID: 9cedee430f22
Revises: cc46c9c1bf21
Create Date: 2023-06-21 23:58:48.022671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cedee430f22'
down_revision = 'cc46c9c1bf21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eyeshadows', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'eyeshadows', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eyeshadows', type_='foreignkey')
    op.drop_column('eyeshadows', 'customer_id')
    # ### end Alembic commands ###
