"""empty message

Revision ID: a0b35f3472c5
Revises: de9b52f2100e
Create Date: 2023-06-21 20:28:09.801008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b35f3472c5'
down_revision = 'de9b52f2100e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eyeshadows', sa.Column('single', sa.Boolean(), nullable=True))
    op.alter_column('eyeshadows', 'palette_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eyeshadows', 'palette_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('eyeshadows', 'single')
    # ### end Alembic commands ###
