"""empty message

Revision ID: cc46c9c1bf21
Revises: a0b35f3472c5
Create Date: 2023-06-21 20:38:31.717646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc46c9c1bf21'
down_revision = 'a0b35f3472c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eyeshadows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('finish', sa.String(length=50), nullable=True),
    sa.Column('form', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('palette_id', sa.Integer(), nullable=True),
    sa.Column('single', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['palette_id'], ['palette.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eyeshadows')
    # ### end Alembic commands ###
