"""empty message

Revision ID: d434a9313993
Revises: 3ec00506a8d2
Create Date: 2023-07-03 09:52:22.860850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd434a9313993'
down_revision = '3ec00506a8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('palette',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'eyeshadows', 'palette', ['palette_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eyeshadows', type_='foreignkey')
    op.drop_table('palette')
    # ### end Alembic commands ###
