"""empty message

Revision ID: de9b52f2100e
Revises: 860ddfe66cea
Create Date: 2023-06-21 20:14:26.957531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9b52f2100e'
down_revision = '860ddfe66cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('eyeshadows_customer_id_fkey', 'eyeshadows', type_='foreignkey')
    op.drop_column('eyeshadows', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eyeshadows', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('eyeshadows_customer_id_fkey', 'eyeshadows', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###
